[General]
Name = RG35XXH Controller
Alias = RG35XXH Gamepad
Class = 0x002508
DiscoverableTimeout = 0
AlwaysPairable = true
PairableTimeout = 0
DeviceID = usb:0x1949:0x0401:0001
ReverseServiceDiscovery = true
NameResolving = true
DebugKeys = false
ControllerMode = dual
MultiProfile = off
FastConnectable = true
Privacy = device
JustWorksRepairing = always
TemporaryTimeout = 30
RefreshDiscovery = false

[Policy]
AutoEnable = true
ReconnectAttempts = 7
ReconnectIntervals = 1,2,4,8,16,32,64
AutoConnectTimeout = 60